https:
  keystore:
    password: "![vXU6kVqqkyappZHqSxmFdg==]"
    key:
      password: "![n/ALlOsSMIYEUd1Yj7AB3Wan4N2zrGhBlLT+1936D+M=]"
      
ngp-sys-request:
  client_secret: ""
  client_id: ""
      